adapters:
  - ws
debug: true
enableVerify: false
verifyKey: WeQ
singleMode: false
cacheSize: 40960
persistenceFactory: 'built-in'
adapterSettings:
  ws:
    host: localhost
    port: 13288
    reversedSyncId: -1
