adapters: 
  - http
  - ws
debug: true
enableVerify: false
verifyKey: WeQ
singleMode: false
cacheSize: 40960
persistenceFactory: 'built-in'
adapterSettings:
  http:
    host: localhost
    port: 8080
    cors: ["*"]
    unreadQueueMaxSize: 1000

  ws:
    host: localhost
    port: 8080
    reversedSyncId: -1
